-- One-shot bootstrap for a brand new Supabase database (RLS disabled).
-- This script creates required tables, grants table privileges, disables RLS,
-- and removes previously created policies (if any).

begin;

create table if not exists public.individual (
  id bigint generated by default as identity primary key,
  name text,
  guardian text,
  address text,
  district text,
  pin text,
  age text,
  occupation text,
  contact text,
  email text,
  "physicallyFit" text,
  religion text,
  "foodPreference" text,
  "campExperience" text,
  "natureOfCamper" text,
  amount text,
  course text,
  created_at timestamptz not null default now()
);

create table if not exists public.organization (
  id bigint generated by default as identity primary key,
  "organizationName" text,
  "organizationAddress" text,
  "organizationContact" text,
  "organizationEmail" text,
  "organizationContactPerson" text,
  name text,
  guardian text,
  address text,
  district text,
  pin text,
  age text,
  occupation text,
  contact text,
  email text,
  "physicallyFit" text,
  religion text,
  "foodPreference" text,
  "campExperience" text,
  "natureOfCamper" text,
  amount text,
  course text,
  created_at timestamptz not null default now()
);

create table if not exists public.approved_admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint approved_admin_users_email_lowercase check (email = lower(email))
);

grant usage on schema public to anon, authenticated, service_role;

revoke all on table public.individual from anon, authenticated, service_role;
revoke all on table public.organization from anon, authenticated, service_role;
revoke all on table public.approved_admin_users from anon, authenticated, service_role;

grant insert on table public.individual to anon;
grant insert on table public.organization to anon;

grant insert, select, update, delete on table public.individual to service_role;
grant insert, select, update, delete on table public.organization to service_role;
grant select, insert, update, delete on table public.approved_admin_users to service_role;

grant usage, select on sequence public.individual_id_seq to anon, service_role;
grant usage, select on sequence public.organization_id_seq to anon, service_role;
grant usage, select on sequence public.approved_admin_users_id_seq to service_role;

alter table if exists public.individual disable row level security;
alter table if exists public.organization disable row level security;

drop policy if exists individual_public_insert on public.individual;
drop policy if exists organization_public_insert on public.organization;
drop policy if exists individual_authenticated_select on public.individual;
drop policy if exists organization_authenticated_select on public.organization;
drop policy if exists individual_authenticated_update on public.individual;
drop policy if exists organization_authenticated_update on public.organization;
drop policy if exists individual_admin_select on public.individual;
drop policy if exists organization_admin_select on public.organization;
drop policy if exists individual_admin_update on public.individual;
drop policy if exists organization_admin_update on public.organization;

commit;
