-- One-shot bootstrap for a brand new Supabase database.
-- This script creates required tables, grants table privileges, enables RLS,
-- and applies public-insert + authenticated read/update policies.

begin;

create table if not exists public.individual (
  id bigint generated by default as identity primary key,
  name text,
  guardian text,
  address text,
  district text,
  pin text,
  age text,
  occupation text,
  contact text,
  email text,
  "physicallyFit" text,
  religion text,
  "foodPreference" text,
  "campExperience" text,
  "natureOfCamper" text,
  amount text,
  course text,
  created_at timestamptz not null default now()
);

create table if not exists public.organization (
  id bigint generated by default as identity primary key,
  "organizationName" text,
  "organizationAddress" text,
  "organizationContact" text,
  "organizationEmail" text,
  "organizationContactPerson" text,
  name text,
  guardian text,
  address text,
  district text,
  pin text,
  age text,
  occupation text,
  contact text,
  email text,
  "physicallyFit" text,
  religion text,
  "foodPreference" text,
  "campExperience" text,
  "natureOfCamper" text,
  amount text,
  course text,
  created_at timestamptz not null default now()
);

grant usage on schema public to anon, authenticated;

revoke all on table public.individual from anon, authenticated;
revoke all on table public.organization from anon, authenticated;

grant insert on table public.individual to anon;
grant insert on table public.organization to anon;

grant select, update on table public.individual to authenticated;
grant select, update on table public.organization to authenticated;

grant usage, select on sequence public.individual_id_seq to anon, authenticated;
grant usage, select on sequence public.organization_id_seq to anon, authenticated;

alter table if exists public.individual enable row level security;
alter table if exists public.organization enable row level security;

drop function if exists public.is_admin_from_jwt();

drop policy if exists individual_public_insert on public.individual;
drop policy if exists organization_public_insert on public.organization;
drop policy if exists individual_authenticated_select on public.individual;
drop policy if exists organization_authenticated_select on public.organization;
drop policy if exists individual_authenticated_update on public.individual;
drop policy if exists organization_authenticated_update on public.organization;
drop policy if exists individual_admin_select on public.individual;
drop policy if exists organization_admin_select on public.organization;
drop policy if exists individual_admin_update on public.individual;
drop policy if exists organization_admin_update on public.organization;

create policy individual_public_insert
  on public.individual
  for insert
  to anon
  with check (true);

create policy organization_public_insert
  on public.organization
  for insert
  to anon
  with check (true);

create policy individual_authenticated_select
  on public.individual
  for select
  to authenticated
  using (true);

create policy organization_authenticated_select
  on public.organization
  for select
  to authenticated
  using (true);

create policy individual_authenticated_update
  on public.individual
  for update
  to authenticated
  using (true)
  with check (true);

create policy organization_authenticated_update
  on public.organization
  for update
  to authenticated
  using (true)
  with check (true);

commit;
