const westBengalDistricts: string[] = [
  'Alipurduar',
  'Bankura',
  'Birbhum',
  'Cooch Behar',
  'Dakshin Dinajpur (South Dinajpur)',
  'Darjeeling',
  'Hooghly',
  'Howrah',
  'Jalpaiguri',
  'Jhargram',
  'Kalimpong',
  'Kolkata',
  'Malda',
  'Murshidabad',
  'Nadia',
  'North 24 Parganas',
  'Paschim Bardhaman (West Bardhaman)',
  'Paschim Medinipur (West Medinipur)',
  'Purba Bardhaman (East Bardhaman)',
  'Purba Medinipur (East Medinipur)',
  'Purulia',
  'South 24 Parganas',
  'Uttar Dinajpur (North Dinajpur)',
];

export default westBengalDistricts;
