begin;

create table if not exists public.individual (
  id bigint generated by default as identity primary key,
  name text,
  guardian text,
  address text,
  district text,
  pin text,
  age text,
  occupation text,
  contact text,
  email text,
  "physicallyFit" text,
  religion text,
  "foodPreference" text,
  "campExperience" text,
  "natureOfCamper" text,
  amount text,
  course text,
  created_at timestamptz not null default now()
);

create table if not exists public.organization (
  id bigint generated by default as identity primary key,
  "organizationName" text,
  "organizationAddress" text,
  "organizationContact" text,
  "organizationEmail" text,
  "organizationContactPerson" text,
  name text,
  guardian text,
  address text,
  district text,
  pin text,
  age text,
  occupation text,
  contact text,
  email text,
  "physicallyFit" text,
  religion text,
  "foodPreference" text,
  "campExperience" text,
  "natureOfCamper" text,
  amount text,
  course text,
  created_at timestamptz not null default now()
);

commit;
