begin;

create table if not exists public.approved_admin_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  is_active boolean not null default true,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint approved_admin_users_email_lowercase check (email = lower(email))
);

revoke all on table public.approved_admin_users from anon, authenticated, service_role;
grant select, insert, update, delete on table public.approved_admin_users to service_role;

grant usage, select on sequence public.approved_admin_users_id_seq to service_role;

commit;
